/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.BanDAO;
import DAO.HoaDonDAO;
import DAO.LoaiSPDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamDAO;
import POJO.Ban;
import POJO.ChiTietHD;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class MainQuanCaPhe extends javax.swing.JFrame {

    /**
     * Creates new form MainQuanCaPhe
     */
    
    Vector tblDataBan = new Vector();
    Vector tblTitleBan = new Vector();
    Vector tblDataHD = new Vector();
    Vector tblTitleHD = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<Ban> dsb = BanDAO.getDSB();
    static ArrayList<ChiTietHD> dscthd;
    public MainQuanCaPhe() {
        initComponents();
        bangBan();
        laydulieuBan(dsb);
        create_cboLoaiSP();
        create_cboMaNV();
        bangHD();
        tbl_HD.setModel(new DefaultTableModel(null, tblTitleHD));
        create_cboMaHD();

    }

    public void bangBan(){
        tblTitleBan.add("STT"); tblTitleBan.add("Mã bàn"); 
        tblTitleBan.add("Tên bàn"); tblTitleBan.add("Trạng thái"); 
    }
    public void laydulieuBan(ArrayList<Ban> dsb){
        tblDataBan.removeAllElements();
        int j = 0;
        for(Ban i : dsb){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMaban()); 
            v.add(i.getTenban()); v.add(i.getTrangthai());
            tblDataBan.add(v);
            j++;
        }
        tbl_Ban.setModel(new DefaultTableModel(tblDataBan, tblTitleBan));
    }
    
    public void bangHD(){
        tblTitleHD.add("STT"); tblTitleHD.add("Mã món"); tblTitleHD.add("Tên món"); 
        tblTitleHD.add("Số lượng"); tblTitleHD.add("Giá tiền"); 
        tblTitleHD.add("Thành tiền");
    }
    public void laydulieuHD(ArrayList<ChiTietHD> cthd){
        tblDataHD.removeAllElements();
        int j = 0;
        for(ChiTietHD i : cthd){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMasp()); v.add(i.getTensp()); 
            v.add(i.getSoluong()); v.add(i.getGiatien());
            v.add(i.getThanhtien());
            tblDataHD.add(v);
            j++;
        }
        tbl_HD.setModel(new DefaultTableModel(tblDataHD, tblTitleHD));
    }
    public void create_cboLoaiSP(){
        ArrayList<String> dstenlsp = LoaiSPDAO.XuatTenLSP();
        for(String i:dstenlsp){
            cbo_LoaiSP.addItem(i);
        }
    }
    public void create_cboSP(String tenlsp){
        cbo_TenSP.removeAllItems();
        ArrayList<String> dstensp = SanPhamDAO.XuatTenSP(tenlsp);
        for(String i:dstensp){
            cbo_TenSP.addItem(i);
        }
    }

    public void create_cboMaNV(){
        ArrayList<String> dsmnv = NhanVienDAO.XuatMaNV();
        for(String i:dsmnv){
            cbo_MaNV.addItem(i);
        }
    }
    public void create_cboMaHD(){
        cbo_MaHD.removeAllItems();
        ArrayList<String> dsmahd = HoaDonDAO.XuatHD_ChuaThanhToan();
        for(String i:dsmahd){
            cbo_MaHD.addItem(i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ban = new javax.swing.JTable();
        cbo_LoaiSP = new javax.swing.JComboBox<>();
        cbo_TenSP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_SL = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HD = new javax.swing.JTable();
        btn_ThemMon = new javax.swing.JButton();
        btn_Chuyen_DatBan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        cbo_MaNV = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_MaBan = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JLabel();
        txt_GiamGia = new javax.swing.JTextField();
        cbo_MaHD = new javax.swing.JComboBox<>();
        btn_ThemHD = new javax.swing.JButton();
        lbl_SuaGG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CÀ PHÊ TÔM TÍT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafelogo.png"))); // NOI18N

        tbl_Ban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Ban);

        cbo_LoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_LoaiSPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Số lượng");

        jSpinner_SL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_SLKeyTyped(evt);
            }
        });

        tbl_HD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_HD);

        btn_ThemMon.setBackground(new java.awt.Color(255, 0, 0));
        btn_ThemMon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ThemMon.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemMon.setText("Thêm món");
        btn_ThemMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMonActionPerformed(evt);
            }
        });

        btn_Chuyen_DatBan.setBackground(new java.awt.Color(255, 0, 0));
        btn_Chuyen_DatBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Chuyen_DatBan.setForeground(new java.awt.Color(255, 255, 255));
        btn_Chuyen_DatBan.setText("Chuyển/Đặt bàn");
        btn_Chuyen_DatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Chuyen_DatBanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Giảm giá (%)");

        btn_ThanhToan.setBackground(new java.awt.Color(255, 0, 0));
        btn_ThanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setText("Thanh toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mã nhân viên");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mã hóa đơn");

        btn_Sua.setBackground(new java.awt.Color(255, 0, 0));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        cbo_MaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("VND");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mã bàn đã chọn :");

        lbl_MaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt_TongTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txt_GiamGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_GiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_SLKeyTyped(evt);
            }
        });

        cbo_MaHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbo_MaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_MaHDActionPerformed(evt);
            }
        });

        btn_ThemHD.setBackground(new java.awt.Color(255, 0, 0));
        btn_ThemHD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ThemHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemHD.setText("Thêm hóa đơn");
        btn_ThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemHDActionPerformed(evt);
            }
        });

        lbl_SuaGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset.png"))); // NOI18N
        lbl_SuaGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SuaGGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_MaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Chuyen_DatBan)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_GiamGia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SuaGG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_LoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner_SL))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_MaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_ThemMon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ThemHD)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_MaHD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_LoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(cbo_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemMon)
                            .addComponent(btn_ThemHD))
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(btn_Sua)
                                    .addComponent(btn_Xoa)
                                    .addComponent(txt_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_SuaGG))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btn_Chuyen_DatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_MaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner_SLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_SLKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jSpinner_SLKeyTyped

    public void TaoHD(String mahd, String manv){
        
        String sql = "insert into HoaDon(MaHD,MaNV) values('"+mahd+"','"+manv+"')";
        int kq=HoaDonDAO.ThemXoaSua(sql);
        if(kq!=-1){
            System.out.println("Thêm hóa đơn "+mahd+" thành công !");
        }
    }
    public void XuatGTHD(String mahd){
        
        String[] tachchuoi = HoaDonDAO.XuatGG_TongTien(mahd).split(" ");
        String giamgia = tachchuoi[0];
        String tongtien = tachchuoi[1];
        
        txt_TongTien.setText(tongtien);
        txt_GiamGia.setText(giamgia);
        
    }
    public void TaoCTHD(String mahd, String masp){

        String sql = "insert into ChiTietHoaDon(MaHD,MaSP) values('"+mahd+"','"+masp+"')\n" +
                     "exec TinhThanhTien '"+mahd+"', '"+masp+"'\n"+
                     "exec tongtien_hoadon '"+mahd+"'";
        int kq=HoaDonDAO.ThemXoaSua(sql);
        if(kq!=-1){
            System.out.println("Thêm sản phẩm mã "+masp+" vào hóa đơn mã "+mahd+" thành công !");
        }
        else{
            String sql_UpdateSLSP = "update ChiTietHoaDon set SoLuong = SoLuong + 1  where MaHD = '"+mahd+"' and MaSP = '"+masp+"'\n" +
                     "exec TinhThanhTien '"+mahd+"', '"+masp+"'\n"+
                     "exec tongtien_hoadon '"+mahd+"'";
            HoaDonDAO.ThemXoaSua(sql_UpdateSLSP);
        }
        dscthd = HoaDonDAO.getDSCTHD(cbo_MaHD.getSelectedItem().toString());
        laydulieuHD(dscthd);
        XuatGTHD(mahd);
    }
    private void btn_ThemMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMonActionPerformed
        // TODO add your handling code here:
        int n = 100000;
        String mahd = "";
        String manv = cbo_MaNV.getSelectedItem().toString();
        String masp = SanPhamDAO.XuatMaSP(cbo_TenSP.getSelectedItem().toString());
        if(cbo_MaHD.getItemCount()==0)
        {

            for(int i=0;i<n;i++){
                mahd = "HD"+(i+1);
                if(HoaDonDAO.XacNhanHD(mahd)==0){
                    break;
                }
            }

            TaoHD(mahd, manv);
            cbo_MaHD.addItem(mahd);
            TaoCTHD(mahd,masp);
        }
        else{
            TaoCTHD(cbo_MaHD.getSelectedItem().toString(),masp);
        }
    }//GEN-LAST:event_btn_ThemMonActionPerformed

    private void cbo_LoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_LoaiSPActionPerformed
        // TODO add your handling code here:
        String tenlsp = cbo_LoaiSP.getSelectedItem().toString();
        create_cboSP(tenlsp);
    }//GEN-LAST:event_cbo_LoaiSPActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(tbl_HD.getSelectedRowCount()==1)
        {
            String mahd = cbo_MaHD.getSelectedItem().toString();
            String masp = tbl_HD.getValueAt(tbl_HD.getSelectedRow(), 1).toString();
            String sql =
                    "delete from ChiTietHoaDon where MaHD = '"+mahd+"' and MaSP = '"+masp+"'\n"+
                    "exec TinhThanhTien '"+mahd+"', '"+masp+"'\n"+
                    "exec tongtien_hoadon '"+mahd+"'\n";
            if(HoaDonDAO.ThemXoaSua(sql)!=-1){
                System.out.println("Xóa sản phẩm có mã "+masp+" thành công !");
                dscthd = HoaDonDAO.getDSCTHD(cbo_MaHD.getSelectedItem().toString());
                laydulieuHD(dscthd);
                XuatGTHD(mahd);
                int value = 0;
                txt_GiamGia.setText(value+"");
            }else{
                JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
            };

            
        }else{
            if(tbl_HD.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        String mahd = cbo_MaHD.getSelectedItem().toString();
         String masp = tbl_HD.getValueAt(tbl_HD.getSelectedRow(), 1).toString();
        int sl = Integer.parseInt(jSpinner_SL.getValue().toString());
            String sql_UpdateSLSP = "update ChiTietHoaDon set SoLuong = "+sl+" where MaHD = '"+mahd+"' and MaSP='"+masp+"'\n" +
                         "exec TinhThanhTien '"+mahd+"', '"+masp+"'\n"+
                    "exec tongtien_hoadon '"+mahd+"'\n";
            HoaDonDAO.ThemXoaSua(sql_UpdateSLSP);
            dscthd = HoaDonDAO.getDSCTHD(mahd);
            laydulieuHD(dscthd);
            XuatGTHD(mahd);
            
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_Chuyen_DatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Chuyen_DatBanActionPerformed
        // TODO add your handling code here:
        String mahd = cbo_MaHD.getSelectedItem().toString();
        if(tbl_Ban.getSelectedRowCount()==1){
            String trangthai = tbl_Ban.getValueAt(tbl_Ban.getSelectedRow(), 3).toString();



            if(trangthai.equals("Đang phục vụ"))
                JOptionPane.showMessageDialog(this, "Bàn đã có khách hàng","Thông báo",2);
            else
            {
                String maban = tbl_Ban.getValueAt(tbl_Ban.getSelectedRow(), 1).toString().trim();
                if(HoaDonDAO.XuatMaBan(mahd)=="")
                {
                    String sqlUpdateMaBan = "update HoaDon set MaBan = '"+maban+"' where MaHD = '"+mahd+"'";
                    HoaDonDAO.ThemXoaSua(sqlUpdateMaBan);
                    lbl_MaBan.setText(maban);

                    String mabanchon = lbl_MaBan.getText();
                    String sqlUpdateTTBan = "update Ban set TrangThai = N'Đang phục vụ' where MaBan = '"+mabanchon+"'";
                    HoaDonDAO.ThemXoaSua(sqlUpdateTTBan);
                }
                else
                {
                    String mabanchon = lbl_MaBan.getText();
                    String sql = "exec doiban '"+mahd+"','"+mabanchon+"','"+maban+"'";
                    HoaDonDAO.ThemXoaSua(sql);
                    dsb = BanDAO.getDSB();
                    laydulieuBan(dsb);
                    lbl_MaBan.setText(mabanchon);
                }
            }
        }else{
            if(tbl_Ban.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần đặt/chuyển bàn","Thông báo",2);
        }
        
    }//GEN-LAST:event_btn_Chuyen_DatBanActionPerformed

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thanh toán không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String mahd = cbo_MaHD.getSelectedItem().toString();
                String mabanchon = lbl_MaBan.getText();
                if(mabanchon.equals(""))
                    JOptionPane.showMessageDialog(this, "Chưa chọn mã bàn khách đã dùng bữa","Thông báo",2);
                else
                {
                    if(HoaDonDAO.DemSLMonHD(mahd)==0)
                        JOptionPane.showMessageDialog(this, "Chưa chọn món cho hóa đơn","Thông báo",2);
                    else{
                        String sql = "update HoaDon set NgayLapHD = GETDATE(), TinhTrang=N'Đã thanh toán' where MaHD = '"+mahd+"'\n"+
                                    "update Ban set TrangThai = N'Còn trống' where MaBan = '"+mabanchon+"'";
                        HoaDonDAO.ThemXoaSua(sql);
                        JOptionPane.showMessageDialog(this, "Thanh toán thành công !");

                        cbo_MaHD.removeItem(mahd);
                        tbl_HD.setModel(new DefaultTableModel(null, tblTitleHD));
                        lbl_MaBan.setText("");
                        txt_TongTien.setText("");
                        dsb = BanDAO.getDSB();
                        laydulieuBan(dsb);
                        int value = 0;
                        jSpinner_SL.setValue(Integer.valueOf(value));
                        txt_GiamGia.setText(value+"");
                    }
                    
                }
        }
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void tbl_HDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HDMouseClicked
        // TODO add your handling code here:
        int sl = Integer.parseInt(tbl_HD.getValueAt(tbl_HD.getSelectedRow(), 3).toString());
        jSpinner_SL.setValue(sl);
    }//GEN-LAST:event_tbl_HDMouseClicked

    private void cbo_MaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_MaHDActionPerformed
        // TODO add your handling code here:
        String mahd = cbo_MaHD.getSelectedItem().toString();
        dscthd = HoaDonDAO.getDSCTHD(mahd);
        laydulieuHD(dscthd);
        dsb = BanDAO.getDSB();
        laydulieuBan(dsb);
        int n = 0;
        jSpinner_SL.setValue(n);
        XuatGTHD(mahd);
        String maban = HoaDonDAO.XuatMaBan(mahd);
        lbl_MaBan.setText(maban);
    }//GEN-LAST:event_cbo_MaHDActionPerformed

    private void btn_ThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemHDActionPerformed
        // TODO add your handling code here:
        String mahd = "";
        String manv = cbo_MaNV.getSelectedItem().toString(); 
        int n = 100000;
        for(int i=0;i<n;i++){
                mahd = "HD"+(i+1);
                if(HoaDonDAO.XacNhanHD(mahd)==0){
                    break;
                }
            }

            TaoHD(mahd, manv);
            cbo_MaHD.addItem(mahd);
    }//GEN-LAST:event_btn_ThemHDActionPerformed

    private void lbl_SuaGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaGGMouseClicked
        // TODO add your handling code here:
        String mahd = cbo_MaHD.getSelectedItem().toString();
        int giamgia=Integer.parseInt(txt_GiamGia.getText());
        String[] tachchuoi = HoaDonDAO.XuatGG_TongTien(mahd).split(" ");
        int tongtien = Integer.parseInt(tachchuoi[1]);
        int gg=0;
        
        if(giamgia>=0 && giamgia<=100 ){
            float kq = (float)giamgia/100*tongtien;
            gg = (int)kq;
        }
        else
            JOptionPane.showMessageDialog(this, "Giảm giá theo % chỉ có thể từ 0 đến 100 !","Thông báo",2);
        
        String sql = "update HoaDon set GiamGia = "+gg+" where MaHD = '"+mahd+"'\n"+
                         "exec tongtien_hoadon '"+mahd+"'";
        HoaDonDAO.ThemXoaSua(sql);
        XuatGTHD(mahd);
        txt_GiamGia.setText(giamgia+"");
    }//GEN-LAST:event_lbl_SuaGGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainQuanCaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainQuanCaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainQuanCaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainQuanCaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainQuanCaPhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Chuyen_DatBan;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_ThemHD;
    private javax.swing.JButton btn_ThemMon;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_LoaiSP;
    private javax.swing.JComboBox<String> cbo_MaHD;
    private javax.swing.JComboBox<String> cbo_MaNV;
    private javax.swing.JComboBox<String> cbo_TenSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_SL;
    private javax.swing.JLabel lbl_MaBan;
    private javax.swing.JLabel lbl_SuaGG;
    private javax.swing.JTable tbl_Ban;
    private javax.swing.JTable tbl_HD;
    private javax.swing.JTextField txt_GiamGia;
    private javax.swing.JLabel txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
